---
name: CI workflow
"on": [push]
env:
  CFLAGS: -fdiagnostics-color
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: install-deps
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            gtk-doc-tools \
            libgirepository1.0-dev \
            libgtk-3-dev \
            meson \
            valac

      - uses: actions/checkout@v2

      - name: configure
        run: meson _build

      - name: build
        run: |
          ninja -C _build
          ninja -C _build ratify-2-doc
          rm _build/docs/reference/html/ratify-2.devhelp2

      - name: test
        run: xvfb-run -a meson test -C _build

      - if: github.ref_name == 'main'
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: _build/docs/reference/html
